import fs from "node:fs/promises";
import { execFile } from "node:child_process";
import path from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
const plan = JSON.parse(await fs.readFile(path.join(rootDir, "runtime-check-plan.json"), "utf8"));
const apiContracts = JSON.parse(await fs.readFile(path.join(rootDir, "api-contracts.json"), "utf8"));
const reportPath = path.join(rootDir, plan.report.outputPath);
const execFileAsync = promisify(execFile);

const envVars = Object.fromEntries(Object.entries(plan.env).filter(([, value]) => typeof value === "string"));
const state = {
  createdPrimary: null,
  latestPrimary: null,
  exportJob: null
};

function envValue(name) {
  const direct = process.env[name];
  if (direct) {
    return direct;
  }

  const fallbackMap = {
    TOPOGRAM_API_BASE_URL: process.env.PUBLIC_TOPOGRAM_API_BASE_URL || "http://localhost:3000",
    TOPOGRAM_WEB_BASE_URL: process.env.PUBLIC_TOPOGRAM_WEB_BASE_URL || `http://localhost:${process.env.WEB_PORT || "5173"}`,
    TOPOGRAM_DEMO_CONTAINER_ID: process.env.PUBLIC_TOPOGRAM_DEMO_CONTAINER_ID || process.env.PUBLIC_TOPOGRAM_DEMO_PROJECT_ID || "",
    TOPOGRAM_DEMO_PRIMARY_ID: process.env.PUBLIC_TOPOGRAM_DEMO_PRIMARY_ID || process.env.PUBLIC_TOPOGRAM_DEMO_TASK_ID || process.env.PUBLIC_TOPOGRAM_DEMO_ISSUE_ID || "",
    TOPOGRAM_DEMO_USER_ID: process.env.PUBLIC_TOPOGRAM_DEMO_USER_ID || "",
    TOPOGRAM_AUTH_USER_ID: process.env.TOPOGRAM_DEMO_USER_ID || ""
  };

  return fallbackMap[name] || "";
}

function apiBase() {
  return envValue(plan.env.apiBase);
}

function webBase() {
  return envValue(plan.env.webBase);
}

function stackStartHint() {
  return "Start the generated stack with 'npm run dev' from the app bundle, or 'npm run app:dev' from the project root, then rerun this command.";
}

function describeFetchError(error) {
  if (error?.cause?.code) {
    return error.cause.code;
  }
  if (Array.isArray(error?.cause?.errors) && error.cause.errors.length > 0) {
    return [...new Set(error.cause.errors.map((entry) => entry.code).filter(Boolean))].join(", ");
  }
  return error instanceof Error ? error.message : String(error);
}

async function fetchWithStackHint(url, init, label) {
  try {
    return await fetch(url, init);
  } catch (error) {
    throw new Error(`${label} is not reachable at ${url.toString()}. ${stackStartHint()} Original error: ${describeFetchError(error)}`);
  }
}

function resolveCheckPath(pathTemplate) {
  return String(pathTemplate || "")
    .replace(/$env:([A-Z0-9_]+)/g, (_, name) => encodeURIComponent(envValue(name)))
    .replace(/$state:primary_id/g, encodeURIComponent(String(state.latestPrimary?.id || state.createdPrimary?.id || "")));
}

function authToken() {
  return envValue("TOPOGRAM_AUTH_TOKEN");
}

function pathParamValue(token) {
  if (typeof token !== "string") {
    return token;
  }
  if (token.startsWith("$env:")) {
    return envValue(token.slice(5));
  }
  if (token === "$state:primary_id") {
    return state.latestPrimary?.id || state.createdPrimary?.id || "";
  }
  return token;
}

function contractFor(capabilityId) {
  const contract = apiContracts[capabilityId];
  if (!contract) {
    throw new Error(`Missing API contract for ${capabilityId}`);
  }
  return contract;
}

function buildUrl(base, endpointPath, pathParams = {}) {
  let resolvedPath = endpointPath;
  for (const [name, rawValue] of Object.entries(pathParams)) {
    const value = pathParamValue(rawValue);
    resolvedPath = resolvedPath.replace(`:${name}`, encodeURIComponent(String(value)));
  }
  return new URL(resolvedPath, base);
}

function inferPathParams(contract, overrides = {}) {
  const params = {};
  for (const field of contract.requestContract?.transport?.path || []) {
    if (Object.prototype.hasOwnProperty.call(overrides, field.name)) {
      params[field.transport.wireName] = overrides[field.name];
      continue;
    }
    if (
      field.name.endsWith("_id") &&
      field.transport?.wireName === "id" &&
      field.name !== "job_id"
    ) {
      params[field.transport.wireName] = "$state:primary_id";
      continue;
    }
    if (field.name === "job_id") {
      throw new Error("Runtime checks do not support job_id paths in v1");
    }
  }
  return params;
}

function createPayload(overrides = {}) {
  return {
    title: "Runtime Check Task",
    description: "Generated by the richer runtime check bundle.",
    priority: "high",
    project_id: envValue(plan.env.demoContainerId),
    ...(envValue(plan.env.demoUserId) ? { owner_id: envValue(plan.env.demoUserId) } : {}),
    ...overrides
  };
}

function assertCondition(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

function assertErrorResponse(responseBody, expectedCode, label) {
  assertCondition(responseBody && typeof responseBody === "object", `${label} did not return a JSON object body`);
  assertCondition(responseBody.error && typeof responseBody.error === "object", `${label} did not include an error object`);
  assertCondition(typeof responseBody.error.code === "string" && responseBody.error.code.length > 0, `${label} did not include an error code`);
  assertCondition(typeof responseBody.error.message === "string" && responseBody.error.message.length > 0, `${label} did not include an error message`);
  if (expectedCode) {
    assertCondition(responseBody.error.code === expectedCode, `${label} expected error code ${expectedCode}, got ${responseBody.error.code}`);
  }
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function appleScriptString(value) {
  return JSON.stringify(String(value ?? ""));
}

async function runSafariBrowserCheck(definition) {
  if (process.platform !== "darwin") {
    throw new Error("web_browser_contract is only supported on macOS local stacks");
  }

  const targetUrl = new URL(resolveCheckPath(definition.path), webBase()).toString();
  const waitMs = Number(process.env.TOPOGRAM_BROWSER_WAIT_MS || "8000");
  const pollMs = Number(process.env.TOPOGRAM_BROWSER_POLL_MS || "250");
  const pollLimit = Math.max(1, Math.ceil(waitMs / pollMs));
  const pollDelaySeconds = pollMs / 1000;
  const browserApp = process.env.TOPOGRAM_BROWSER_APP || "Safari";
  const script = [
    `set targetUrl to ${appleScriptString(targetUrl)}`,
    `set expectedText to ${appleScriptString(definition.expectText || "")}`,
    `set forbiddenText to ${appleScriptString(definition.expectNotText || "")}`,
    `set pollLimit to ${appleScriptString(pollLimit)} as integer`,
    `set pollDelay to ${appleScriptString(pollDelaySeconds)} as real`,
    `tell application ${appleScriptString(browserApp)}`,
    "activate",
    "set runtimeDoc to make new document with properties {URL:targetUrl}",
    "repeat with attempt from 1 to pollLimit",
    "delay pollDelay",
    "try",
    "set bodyText to do JavaScript \"document.body ? document.body.innerText : ''\" in runtimeDoc",
    "if (expectedText is \"\" or bodyText contains expectedText) and (forbiddenText is \"\" or bodyText does not contain forbiddenText) then exit repeat",
    "end try",
    "end repeat",
    "set finalText to do JavaScript \"document.body ? document.body.innerText : ''\" in runtimeDoc",
    "close runtimeDoc",
    "return finalText",
    "end tell"
  ];
  const args = script.flatMap((line) => ["-e", line]);
  const { stdout, stderr } = await execFileAsync("osascript", args);
  if (stderr && stderr.trim()) {
    throw new Error(`browser check failed: ${stderr.trim()}`);
  }
  return stdout.trim();
}

async function waitForExportJob(jobId, { attempts = 10, delayMs = 25 } = {}) {
  for (let attempt = 0; attempt < attempts; attempt += 1) {
    const { response, responseBody } = await requestContract("cap_get_task_export_job", {
      pathParams: {
        job_id: jobId
      }
    });
    assertCondition(response.status === 200, `get export job expected 200 during polling, got ${response.status}`);
    if (responseBody?.status === "completed" && responseBody?.download_url) {
      return responseBody;
    }
    await sleep(delayMs);
  }
  throw new Error("export job did not reach completed status in time");
}

async function parseResponseBody(response) {
  const text = await response.text();
  if (!text) {
    return null;
  }
  const contentType = response.headers.get("content-type") || "";
  if (contentType.includes("application/json")) {
    return JSON.parse(text);
  }
  return text;
}

async function requestContract(capabilityId, { payload = null, pathParams = null, headers = {} } = {}) {
  const contract = contractFor(capabilityId);
  const resolvedPathParams = pathParams || inferPathParams(contract);
  const url = buildUrl(apiBase(), contract.endpoint.path, resolvedPathParams);
  const requestHeaders = new Headers(headers);
  if ((contract.endpoint.authz || []).length > 0 && authToken() && !requestHeaders.has("Authorization")) {
    requestHeaders.set("Authorization", `Bearer ${authToken()}`);
  }
  let body;
  if (payload && (contract.requestContract?.transport?.body || []).length > 0) {
    requestHeaders.set("content-type", "application/json");
    body = JSON.stringify(payload);
  }
  const response = await fetchWithStackHint(url, {
    method: contract.endpoint.method,
    headers: requestHeaders,
    body
  }, "api service");
  const responseBody = await parseResponseBody(response);
  return { contract, response, responseBody, url: url.toString() };
}

function preconditionStatusFor(contract) {
  return contract.endpoint.preconditions?.[0]?.error || 412;
}

function checkResultTemplate(definition) {
  return {
    id: definition.id,
    kind: definition.kind,
    mandatory: definition.mandatory !== false,
    mutating: Boolean(definition.mutating),
    ok: null,
    skipped: false,
    durationMs: 0,
    error: null,
    resources: {}
  };
}

async function runCheck(definition) {
  const startedAt = Date.now();
  const result = checkResultTemplate(definition);
  try {
    if (definition.id === "required_env") {
      const missing = plan.env.required.filter((name) => !envValue(name));
      assertCondition(missing.length === 0, `Missing required environment variables: ${missing.join(", ")}`);
    } else if (definition.kind === "web_contract") {
      const response = await fetchWithStackHint(new URL(resolveCheckPath(definition.path), webBase()), undefined, "web app");
      const body = await response.text();
      assertCondition(response.status === definition.expectStatus, `web readiness expected ${definition.expectStatus}, got ${response.status}`);
      assertCondition(body.includes(definition.expectText), `web readiness did not include expected text: ${definition.expectText}`);
      if (definition.expectNotText) {
        assertCondition(!body.includes(definition.expectNotText), `web readiness unexpectedly included text: ${definition.expectNotText}`);
      }
    } else if (definition.kind === "web_browser_contract") {
      const bodyText = await runSafariBrowserCheck(definition);
      if (definition.expectText) {
        assertCondition(bodyText.includes(definition.expectText), `browser check did not include expected text: ${definition.expectText}`);
      }
      if (definition.expectNotText) {
        assertCondition(!bodyText.includes(definition.expectNotText), `browser check unexpectedly included text: ${definition.expectNotText}`);
      }
    } else if (definition.kind === "api_health") {
      const response = await fetchWithStackHint(new URL(definition.path, apiBase()), undefined, "api service");
      const responseBody = await parseResponseBody(response);
      assertCondition(response.status === definition.expectStatus, `api health expected ${definition.expectStatus}, got ${response.status}`);
      assertCondition(responseBody?.ok === definition.expectOk, "api health did not report ok");
    } else if (definition.kind === "api_ready") {
      const response = await fetchWithStackHint(new URL(definition.path, apiBase()), undefined, "api service");
      const responseBody = await parseResponseBody(response);
      assertCondition(response.status === definition.expectStatus, `api readiness expected ${definition.expectStatus}, got ${response.status}`);
      assertCondition(responseBody?.ready === definition.expectReady, "api readiness did not report ready");
    } else if (definition.id === "api_seed_task_ready") {
      const { contract, response, responseBody } = await requestContract(definition.capabilityId, {
        pathParams: inferPathParams(contractFor(definition.capabilityId), definition.pathParams)
      });
      assertCondition(response.status === contract.endpoint.successStatus, `seed task readiness expected ${contract.endpoint.successStatus}, got ${response.status}`);
      assertCondition(responseBody?.id === envValue(plan.env.demoPrimaryId), "seed task readiness did not return the expected demo task");
    } else if (definition.id === "create_task") {
      const { contract, response, responseBody } = await requestContract(definition.capabilityId, {
        payload: createPayload(),
        headers: {
          "Idempotency-Key": crypto.randomUUID()
        }
      });
      assertCondition(response.status === contract.endpoint.successStatus, `create task expected ${contract.endpoint.successStatus}, got ${response.status}`);
      assertCondition(responseBody?.id, "create task response did not include id");
      assertCondition(responseBody?.project_id === envValue(plan.env.demoContainerId), "create task response used the wrong project");
      assertCondition(responseBody?.priority === "high", "create task did not persist priority");
      assertCondition(responseBody?.updated_at, "create task response did not include updated_at");
      state.createdPrimary = responseBody;
      state.latestPrimary = responseBody;
      result.resources.primaryId = responseBody.id;
    } else if (definition.id === "get_created_task") {
      const { contract, response, responseBody } = await requestContract(definition.capabilityId);
      assertCondition(response.status === contract.endpoint.successStatus, `get task expected ${contract.endpoint.successStatus}, got ${response.status}`);
      assertCondition(responseBody?.id === state.latestPrimary?.id, "get task did not return the created task");
      assertCondition(responseBody?.title, "get task did not include title");
      assertCondition(responseBody?.priority, "get task did not include priority");
    } else if (definition.id === "list_tasks") {
      const { contract, response, responseBody } = await requestContract(definition.capabilityId);
      assertCondition(response.status === contract.endpoint.successStatus, `list tasks expected ${contract.endpoint.successStatus}, got ${response.status}`);
      assertCondition(Array.isArray(responseBody?.items), "list tasks did not return an items array");
      assertCondition(responseBody.items.some((item) => item.id === state.latestPrimary?.id), "list tasks did not include the created task");
    } else if (definition.id === "export_tasks") {
      const { contract, response, responseBody } = await requestContract(definition.capabilityId, {
        payload: {
          project_id: envValue(plan.env.demoContainerId)
        }
      });
      assertCondition(response.status === contract.endpoint.successStatus, `export tasks expected ${contract.endpoint.successStatus}, got ${response.status}`);
      assertCondition(responseBody?.job_id, "export tasks did not return a job_id");
      assertCondition(responseBody?.status_url, "export tasks did not return a status_url");
      state.exportJob = responseBody;
      result.resources.jobId = responseBody.job_id;
    } else if (definition.id === "get_task_export_job") {
      assertCondition(state.exportJob?.job_id, "get task export job requires a previously created export job");
      const responseBody = await waitForExportJob(state.exportJob.job_id);
      assertCondition(responseBody.job_id === state.exportJob.job_id, "get task export job returned the wrong job");
      assertCondition(responseBody.status === "completed", "get task export job did not complete");
      assertCondition(responseBody.download_url, "get task export job did not return a download_url");
      state.exportJob = responseBody;
      result.resources.jobId = responseBody.job_id;
    } else if (definition.id === "download_task_export") {
      assertCondition(state.exportJob?.job_id, "download task export requires a previously created export job");
      const { contract, response } = await requestContract(definition.capabilityId, {
        pathParams: {
          job_id: state.exportJob.job_id
        }
      });
      const responseBuffer = await response.arrayBuffer();
      assertCondition(response.status === contract.endpoint.successStatus, `download task export expected ${contract.endpoint.successStatus}, got ${response.status}`);
      assertCondition(response.headers.get("content-type")?.includes("application/zip"), "download task export did not return zip content");
      assertCondition(response.headers.get("content-disposition")?.includes("task-export.zip"), "download task export did not include the expected filename");
      assertCondition(responseBuffer.byteLength > 0, "download task export returned an empty body");
      result.resources.jobId = state.exportJob.job_id;
    } else if (definition.id === "project_lookup_ready" || definition.id === "user_lookup_ready") {
      const response = await fetch(new URL(definition.path, apiBase()));
      const responseBody = await parseResponseBody(response);
      assertCondition(response.status === 200, `${definition.id} expected 200, got ${response.status}`);
      assertCondition(Array.isArray(responseBody), `${definition.id} did not return an array`);
      assertCondition(responseBody.length > 0, `${definition.id} returned no options`);
      assertCondition(responseBody.every((item) => item && typeof item.value === "string" && typeof item.label === "string"), `${definition.id} returned malformed lookup options`);
    } else if (definition.id === "update_without_precondition") {
      const contract = contractFor(definition.capabilityId);
      const { response, responseBody } = await requestContract(definition.capabilityId, {
        payload: {
          title: "Runtime Check Task Updated"
        }
      });
      const expected = preconditionStatusFor(contract);
      assertCondition(response.status === expected, `update without precondition expected ${expected}, got ${response.status}`);
      assertErrorResponse(responseBody, contract.endpoint.preconditions?.[0]?.code, "update without precondition");
    } else if (definition.id === "update_with_stale_precondition") {
      const { response, responseBody } = await requestContract(definition.capabilityId, {
        payload: {
          title: "Runtime Check Task Stale Update"
        },
        headers: {
          "If-Match": "1970-01-01T00:00:00.000Z"
        }
      });
      assertCondition(response.status === definition.expectStatus, `update with stale precondition expected ${definition.expectStatus}, got ${response.status}`);
      assertErrorResponse(responseBody, definition.expectErrorCode, "update with stale precondition");
    } else if (definition.id === "update_task") {
      const { contract, response, responseBody } = await requestContract(definition.capabilityId, {
        payload: {
          title: "Runtime Check Task Updated",
          priority: "low"
        },
        headers: {
          "If-Match": state.latestPrimary?.updated_at || ""
        }
      });
      assertCondition(response.status === contract.endpoint.successStatus, `update task expected ${contract.endpoint.successStatus}, got ${response.status}`);
      assertCondition(responseBody?.title === "Runtime Check Task Updated", "update task did not persist the updated title");
      assertCondition(responseBody?.priority === "low", "update task did not persist the updated priority");
      assertCondition(responseBody?.updated_at, "update task did not return updated_at");
      state.latestPrimary = responseBody;
      result.resources.primaryId = responseBody.id;
    } else if (definition.id === "complete_without_precondition") {
      const contract = contractFor(definition.capabilityId);
      const { response, responseBody } = await requestContract(definition.capabilityId, {
        payload: {
          completed_at: new Date().toISOString()
        },
        headers: {
          "Idempotency-Key": crypto.randomUUID()
        }
      });
      const expected = preconditionStatusFor(contract);
      assertCondition(response.status === expected, `complete without precondition expected ${expected}, got ${response.status}`);
      assertErrorResponse(responseBody, contract.endpoint.preconditions?.[0]?.code, "complete without precondition");
    } else if (definition.id === "complete_task") {
      const { contract, response, responseBody } = await requestContract(definition.capabilityId, {
        payload: {
          completed_at: new Date().toISOString()
        },
        headers: {
          "If-Match": state.latestPrimary?.updated_at || "",
          "Idempotency-Key": crypto.randomUUID()
        }
      });
      assertCondition(response.status === contract.endpoint.successStatus, `complete task expected ${contract.endpoint.successStatus}, got ${response.status}`);
      assertCondition(responseBody?.status === "completed", "complete task did not set status to completed");
      assertCondition(responseBody?.updated_at, "complete task did not return updated_at");
      state.latestPrimary = responseBody;
      result.resources.primaryId = responseBody.id;
    } else if (definition.id === "delete_without_precondition") {
      const contract = contractFor(definition.capabilityId);
      const { response, responseBody } = await requestContract(definition.capabilityId);
      const expected = preconditionStatusFor(contract);
      assertCondition(response.status === expected, `delete without precondition expected ${expected}, got ${response.status}`);
      assertErrorResponse(responseBody, contract.endpoint.preconditions?.[0]?.code, "delete without precondition");
    } else if (definition.id === "delete_task") {
      const { contract, response, responseBody } = await requestContract(definition.capabilityId, {
        headers: {
          "If-Match": state.latestPrimary?.updated_at || ""
        }
      });
      assertCondition(response.status === contract.endpoint.successStatus, `delete task expected ${contract.endpoint.successStatus}, got ${response.status}`);
      assertCondition(responseBody?.status === "archived", "delete task did not archive the task");
      state.latestPrimary = responseBody;
      result.resources.primaryId = responseBody.id;
    } else if (definition.id === "invalid_create_returns_4xx") {
      const { response, responseBody } = await requestContract(definition.capabilityId, {
        payload: {
          description: "Missing required fields"
        },
        headers: {
          "Idempotency-Key": crypto.randomUUID()
        }
      });
      assertCondition(Math.floor(response.status / 100) === definition.expectStatusClass, `invalid create expected ${definition.expectStatusClass}xx, got ${response.status}`);
      assertErrorResponse(responseBody, definition.expectErrorCode, "invalid create");
    } else if (definition.id === "get_unknown_task_not_found") {
      const { response, responseBody } = await requestContract(definition.capabilityId, {
        pathParams: {
          id: crypto.randomUUID()
        }
      });
      assertCondition(response.status === definition.expectStatus, `get unknown task expected ${definition.expectStatus}, got ${response.status}`);
      assertErrorResponse(responseBody, definition.expectErrorCode, "get unknown task");
    } else {
      throw new Error(`Unsupported runtime check id: ${definition.id}`);
    }
    result.ok = true;
  } catch (error) {
    result.ok = false;
    result.error = error instanceof Error ? error.message : String(error);
  } finally {
    result.durationMs = Date.now() - startedAt;
  }
  return result;
}

function stageSummary(stageDefinition, checks) {
  const failedMandatory = checks.some((check) => check.ok === false && check.mandatory);
  const skipped = checks.every((check) => check.skipped);
  return {
    id: stageDefinition.id,
    name: stageDefinition.name,
    ok: skipped ? null : !failedMandatory,
    skipped,
    checks
  };
}

function skippedChecksForStage(stageDefinition, reason) {
  return stageDefinition.checks.map((definition) => ({
    ...checkResultTemplate(definition),
    skipped: true,
    error: reason
  }));
}

function logCheck(stageId, result) {
  const icon = result.skipped ? "-" : result.ok ? "[ok]" : "[fail]";
  const suffix = result.error ? ` - ${result.error}` : "";
  console.log(`${icon} ${stageId}:${result.id} (${result.durationMs}ms)${suffix}`);
}

async function writeReport(report) {
  await fs.mkdir(path.dirname(reportPath), { recursive: true });
  await fs.writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");
}

const report = {
  ok: true,
  name: plan.name,
  reportPath: plan.report.outputPath,
  stages: [],
  generatedAt: new Date().toISOString()
};

let stopFurtherStages = false;

for (const stageDefinition of plan.stages) {
  if (stopFurtherStages) {
    const skippedChecks = skippedChecksForStage(stageDefinition, "Skipped because a prior fail-fast stage failed");
    for (const check of skippedChecks) {
      logCheck(stageDefinition.id, check);
    }
    report.stages.push(stageSummary(stageDefinition, skippedChecks));
    continue;
  }

  const checks = [];
  for (const checkDefinition of stageDefinition.checks) {
    const result = await runCheck(checkDefinition);
    checks.push(result);
    logCheck(stageDefinition.id, result);
    if (stageDefinition.failFast && result.ok === false && result.mandatory) {
      stopFurtherStages = true;
      break;
    }
  }

  if (stopFurtherStages && checks.length < stageDefinition.checks.length) {
    const remaining = stageDefinition.checks.slice(checks.length).map((definition) => ({
      ...checkResultTemplate(definition),
      skipped: true,
      error: "Skipped because this stage failed in fail-fast mode"
    }));
    for (const check of remaining) {
      logCheck(stageDefinition.id, check);
    }
    checks.push(...remaining);
  }

  report.stages.push(stageSummary(stageDefinition, checks));
}

report.ok = report.stages.every((stage) => stage.ok !== false);
await writeReport(report);
console.log(JSON.stringify(report, null, 2));

if (!report.ok) {
  process.exitCode = 1;
}
